# For development environment

services:
  db:
    image: postgres:17-trixie # if you need to use normal postgres image
    # image: paradedb/paradedb:0.18.0-pg17 # use latest version when possible
    container_name: django-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "db"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: valkey/valkey:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_dev:/data

  s3:
    image: rustfs/rustfs:1.0.0-alpha.86
    container_name: django-s3
    restart: unless-stopped
    volumes:
      - rustfs_data:/data
    ports:
      - "9000:9000"
    environment:
      RUSTFS_ACCESS_KEY: rustfsadmin
      RUSTFS_SECRET_KEY: rustfsadmin
      RUSTFS_ADDRESS: 0.0.0.0:9000
      RUSTFS_EXTERNAL_ADDRESS: ":9000"
      RUSTFS_CORS_ALLOWED_ORIGINS: "*"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  clickstack:
    image: clickhouse/clickstack-local:2.33.0
    container_name: django-clickstack
    profiles:
      - analytics
    ports:
      - "8080:8080"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - clickstack_db:/data/db
      - clickstack_ch_data:/var/lib/clickhouse
      - clickstack_ch_logs:/var/log/clickhouse-server

  app:
    build:
      context: ..
      dockerfile: dev/Dockerfile
    container_name: django-app
    restart: unless-stopped
    depends_on:
      - db
      - redis
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/db
      - REDIS_URL=redis://redis:6379
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://clickstack:4317
      - OTEL_ENABLED=true
      - VITE_HYPERDX_URL=http://localhost:4318
      - VITE_HYPERDX_SERVICE=django-starter-kit-frontend
    volumes:
      - ..:/app
      - django_venv:/app/.venv
      - frontend_node_modules:/app/frontend/node_modules
    ports:
      - "8000:8000" # Django
      - "5173:5173" # Vite
    networks:
      - default

volumes:
  postgres_data:
  redis_dev:
  rustfs_data:
  django_venv:
  frontend_node_modules:
  clickstack_db:
  clickstack_ch_data:
  clickstack_ch_logs:
