# Generated by Django 5.2 on 2025-08-25 21:57

import apps.users.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('account_deactivation', 'Account Deactivation'), ('account_reactivation', 'Account Reactivation'), ('data_anonymization', 'Data Anonymization'), ('consent_update', 'Consent Update'), ('profile_update', 'Profile Update'), ('email_change', 'Email Change'), ('password_change', 'Password Change')], max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'User Audit Log',
                'verbose_name_plural': 'User Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the user account was deactivated.', null=True, verbose_name='deactivated at'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether the user has verified their email address.', verbose_name='verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='oidc_issuer',
            field=models.URLField(blank=True, help_text='OIDC issuer URL for the identity provider.', max_length=255, null=True, verbose_name='OIDC issuer'),
        ),
        migrations.AddField(
            model_name='user',
            name='oidc_subject',
            field=models.CharField(blank=True, help_text='OIDC subject identifier for external identity providers.', max_length=255, null=True, unique=True, verbose_name='OIDC subject'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False, help_text='Indicates if the user has completed their profile setup.', verbose_name='profile completed'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='_encrypted_phone_number',
            field=models.TextField(blank=True, help_text='Encrypted phone number for privacy protection.', verbose_name='encrypted phone number'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief description of yourself (max 500 characters).', max_length=500, verbose_name='bio'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Your birth date (optional).', null=True, verbose_name='birth date'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='data_processing_consent',
            field=models.BooleanField(default=False, help_text='Consent to process personal data for profile features.', verbose_name='data processing consent'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Your location (city, country, etc.)', max_length=100, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marketing_consent',
            field=models.BooleanField(default=False, help_text='Consent to receive marketing communications.', verbose_name='marketing consent'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_email',
            field=models.BooleanField(default=False, help_text='Whether to display your email publicly.', verbose_name='show email'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_profile',
            field=models.BooleanField(default=True, help_text='Whether your profile is visible to other users.', verbose_name='show profile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User profile picture. Files are stored in MEDIA_ROOT/users/user_<id>/ directory. Depending on configuration, this may be local storage or cloud storage (e.g., AWS S3).', null=True, upload_to=apps.users.models.user_directory_path),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_user_usernam_65d164_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['oidc_subject'], name='users_user_oidc_su_7a27f9_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_user_is_acti_ddda02_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_user_created_cf865c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['deactivated_at'], name='users_user_deactiv_1e71ac_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['show_profile'], name='users_userp_show_pr_f74c32_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['location'], name='users_userp_locatio_3408ca_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['data_processing_consent'], name='users_userp_data_pr_955283_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['marketing_consent'], name='users_userp_marketi_b17372_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['created_at'], name='users_userp_created_72cdd2_idx'),
        ),
        migrations.AddField(
            model_name='userauditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userauditlog',
            index=models.Index(fields=['user', 'action'], name='users_usera_user_id_6525b9_idx'),
        ),
        migrations.AddIndex(
            model_name='userauditlog',
            index=models.Index(fields=['created_at'], name='users_usera_created_48c886_idx'),
        ),
    ]
