# Generated by Django 5.2 on 2025-08-26 21:30

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_users_user_first_n_0186c7_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.MaxLengthValidator(254)], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), django.core.validators.MaxLengthValidator(150)], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='_encrypted_phone_number',
            field=models.TextField(blank=True, help_text='Encrypted phone number for privacy protection.', validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?[1-9]\\d{1,14}$')], verbose_name='encrypted phone number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief description of yourself (max 500 characters).', max_length=500, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Your location (city, country, etc.)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='location'),
        ),
    ]
