# Generated by Django 5.2 on 2025-08-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email_alter_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauditlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
